# HTTP(80) 요청을 HTTPS(443)로 강제 전환(Redirect)
server {
  listen 80;
  server_name i14b104.p.ssafy.io;
  
  # Certbot 인증서 갱신을 위한 경로 허용
  location /.well-known/acme-challenge/ {
      root /var/www/certbot;
  }

  # 위 경로를 제외한 모든 접속은 HTTPS로 리다이렉트
  location / {
      return 301 https://$host$request_uri;
  }
}

# # HTTPS(443) 설정
# server {
#   listen 443 ssl;
#   server_name i14b104.p.ssafy.io;

#   # SSL 인증서 경로 설정
#   ssl_certificate /etc/letsencrypt/live/i14b104.p.ssafy.io/fullchain.pem;
#   ssl_certificate_key /etc/letsencrypt/live/i14b104.p.ssafy.io/privkey.pem;

#   # 보안 최적화 설정
#   ssl_protocols TLSv1.2 TLSv1.3;
#   ssl_prefer_server_ciphers on; 

#   # Frontend
#   location / {
#     proxy_pass http://frontend:3000;
#     proxy_http_version 1.1;

#     # HMR 설정
#     proxy_set_header Upgrade $http_upgrade;
#     proxy_set_header Connection 'upgrade';
#     proxy_set_header Host $host;
#     proxy_set_header X-Forwarded-Proto $scheme;
#   }

#   # Spring Backend API
#   location /api/ {
#     proxy_pass http://backend:8080;
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#   }

#   # OpenVidu
#   location /openvidu/ {
#     proxy_pass http://openvidu-dev:4443/;
    
#     proxy_http_version 1.1;
#     proxy_set_header Upgrade $http_upgrade;
#     proxy_set_header Connection "upgrade";
    
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_set_header X-Forwarded-Proto $scheme;
#   }
# }

# # / -> frontend(3000)
# # /api/ -> backend(8080)
# # /openvidu/ -> openvidu(4443)